version: "3"
services:
    www:
        container_name: practica_web
        hostname: practica.web
        build: ./docker
        ports: 
            - "8000:80"
        volumes:
            - .:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        container_name: practica_db
        hostname: practica.db
        image: 'mysql:8.0'
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: practica
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./docker/dump:/docker-entrypoint-initdb.d
            - ./docker/dump:/var/www/html
        entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        networks:
            - default
    phpmyadmin:
        container_name: practica_phpmyadmin
        hostname: practica.phpmyadmin
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - "8001:80"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test